/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package solution.view;

import com.google.gson.Gson;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import solution.control.RegistryServiceControl;
import solution.model.GetRawTransactionModel;
import solution.model.SignRawTransactionWithWalletModel;
import solution.service.StringsService;

/**
 *
 * @author ssd
 */
public class CreateMultisigTransactionPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateMultisigTransactionPanel
     */
    public CreateMultisigTransactionPanel() {
        initComponents();
        multisigTransactionHexTextField.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateMultisigTransactionLabel = new javax.swing.JLabel();
        transactionIdOfTransferredContractLabel = new javax.swing.JLabel();
        createMultisigTransactionButton = new javax.swing.JButton();
        multisigTransactionHexLabel = new javax.swing.JLabel();
        multisigTransactionHexTextField = new java.awt.TextField();
        transactionIdOfContractSentToMultisigTextField = new java.awt.TextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        multisigTransactionHexTextArea = new javax.swing.JTextArea();
        multisigTransactionHexJTextField = new javax.swing.JTextField();
        textArea1 = new java.awt.TextArea();

        CreateMultisigTransactionLabel.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        CreateMultisigTransactionLabel.setText("Create Multisig Transaction");

        transactionIdOfTransferredContractLabel.setText("Transaction ID of Contract Sent to Multisig:");

        createMultisigTransactionButton.setText("Create");
        createMultisigTransactionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createMultisigTransactionButtonActionPerformed(evt);
            }
        });

        multisigTransactionHexLabel.setText("MultisigTransaction Hex:");

        multisigTransactionHexTextField.setEditable(false);

        multisigTransactionHexTextArea.setColumns(20);
        multisigTransactionHexTextArea.setRows(5);
        jScrollPane1.setViewportView(multisigTransactionHexTextArea);

        multisigTransactionHexJTextField.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(transactionIdOfTransferredContractLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transactionIdOfContractSentToMultisigTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CreateMultisigTransactionLabel)
                            .addComponent(createMultisigTransactionButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(multisigTransactionHexLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(multisigTransactionHexTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(multisigTransactionHexJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 55, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreateMultisigTransactionLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(transactionIdOfTransferredContractLabel)
                    .addComponent(transactionIdOfContractSentToMultisigTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(createMultisigTransactionButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(multisigTransactionHexTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(multisigTransactionHexJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(multisigTransactionHexLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createMultisigTransactionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createMultisigTransactionButtonActionPerformed
        GetRawTransactionModel getRawTransactionModel = RegistryServiceControl.getRawTransaction(transactionIdOfContractSentToMultisigTextField.getText());
        long vout = -1;
        if(getRawTransactionModel.getError() == null){
            vout = getRawTransactionModel.getResult().getVout().get(0).getN();
        }
        vout = getRawTransactionModel.getResult().getVout().get(0).getN();
        String rawTxHex = RegistryServiceControl.createRawTransaction(transactionIdOfContractSentToMultisigTextField.getText(), vout, StringsService.WALLET_ADDRESS_ORD, 0.00008000);
        if (vout == -1){
            multisigTransactionHexTextField.setText("Invalid raw transaction ID");
            multisigTransactionHexTextField.setVisible(true);
        }else{
            multisigTransactionHexTextArea.setWrapStyleWord(true);
            multisigTransactionHexTextField.setText(rawTxHex);
            multisigTransactionHexTextField.setVisible(true);
            multisigTransactionHexTextArea.setText(rawTxHex);
            multisigTransactionHexTextArea.setWrapStyleWord(true);
            textArea1.setText(rawTxHex);
//            multisigTransactionHexJTextField.setW
//            multisigTransactionHexJTextField.setText(rawTxHex);
        }
        
        
    }//GEN-LAST:event_createMultisigTransactionButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CreateMultisigTransactionLabel;
    private javax.swing.JButton createMultisigTransactionButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField multisigTransactionHexJTextField;
    private javax.swing.JLabel multisigTransactionHexLabel;
    private javax.swing.JTextArea multisigTransactionHexTextArea;
    private java.awt.TextField multisigTransactionHexTextField;
    private java.awt.TextArea textArea1;
    private java.awt.TextField transactionIdOfContractSentToMultisigTextField;
    private javax.swing.JLabel transactionIdOfTransferredContractLabel;
    // End of variables declaration//GEN-END:variables
}
