/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package solution.view;

import solution.control.RegistryServiceControl;
import solution.model.GetRawTransactionModel;

/**
 *
 * @author ssd
 */
public class SendContractToMultisigPanelView extends javax.swing.JPanel {
    private String multisigAddress;
    /**
     * Creates new form SendContractToMultisigPanelView
     */
    public SendContractToMultisigPanelView(String multisigAddress) {
        initComponents();
        this.multisigAddress = multisigAddress;
        sentContractTransactionIdTextField.setVisible(false);
        multisigAddressTextField.setText(multisigAddress);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sentContractToMultisigAddressLabel = new javax.swing.JLabel();
        contractTransactionIdLabel = new javax.swing.JLabel();
        contractTransactionIdTextField = new java.awt.TextField();
        sendContractToMultisigButton = new javax.swing.JButton();
        multisigAddressLabel = new javax.swing.JLabel();
        multisigAddressTextField = new java.awt.TextField();
        sentContractTransactionIdLabel = new javax.swing.JLabel();
        sentContractTransactionIdTextField = new java.awt.TextField();

        sentContractToMultisigAddressLabel.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        sentContractToMultisigAddressLabel.setText("Send Contract to Multisig Address");

        contractTransactionIdLabel.setText("Contract Transaction ID:");

        sendContractToMultisigButton.setText("Send");
        sendContractToMultisigButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendContractToMultisigButtonActionPerformed(evt);
            }
        });

        multisigAddressLabel.setText("Multisig Address:");

        multisigAddressTextField.setBackground(new java.awt.Color(242, 242, 242));
        multisigAddressTextField.setEditable(false);

        sentContractTransactionIdLabel.setText("Transaction ID of Contract Sent to Multisig:");

        sentContractTransactionIdTextField.setBackground(new java.awt.Color(242, 242, 242));
        sentContractTransactionIdTextField.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sentContractToMultisigAddressLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(contractTransactionIdLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contractTransactionIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sendContractToMultisigButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(multisigAddressLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(multisigAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sentContractTransactionIdLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sentContractTransactionIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sentContractToMultisigAddressLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contractTransactionIdLabel)
                    .addComponent(contractTransactionIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(multisigAddressLabel)
                    .addComponent(multisigAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(sendContractToMultisigButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sentContractTransactionIdLabel)
                    .addComponent(sentContractTransactionIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sendContractToMultisigButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendContractToMultisigButtonActionPerformed
        long vout = -1;
        GetRawTransactionModel getRawTransactionModel = RegistryServiceControl.getRawTransaction(contractTransactionIdTextField.getText());
        if(getRawTransactionModel.getError() == null){
            vout = getRawTransactionModel.getResult().getVout().get(0).getN();
        }
        String rawTxHex = RegistryServiceControl.createRawTransaction(contractTransactionIdTextField.getText(), vout, multisigAddress, 0.00009000);
        String txIdOfSentContractToMultisig = RegistryServiceControl.decodeRawTransaction(rawTxHex);// not used; just for reference
        String signedTx = RegistryServiceControl.signRawTransactionWithWallet(rawTxHex, "ord");
        String txIdOfSentContract = RegistryServiceControl.sendRawTransaction(signedTx, "ord");
        if (vout == -1){
            sentContractTransactionIdTextField.setText("Invalid contract transaction ID");
            sentContractTransactionIdTextField.setVisible(true);
        }else {
            sentContractTransactionIdTextField.setText(txIdOfSentContract);
            sentContractTransactionIdTextField.setVisible(true);
        }
    }//GEN-LAST:event_sendContractToMultisigButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contractTransactionIdLabel;
    private java.awt.TextField contractTransactionIdTextField;
    private javax.swing.JLabel multisigAddressLabel;
    private java.awt.TextField multisigAddressTextField;
    private javax.swing.JButton sendContractToMultisigButton;
    private javax.swing.JLabel sentContractToMultisigAddressLabel;
    private javax.swing.JLabel sentContractTransactionIdLabel;
    private java.awt.TextField sentContractTransactionIdTextField;
    // End of variables declaration//GEN-END:variables
}
