/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package solution.view;

import solution.control.RegistryServiceControl;
import solution.model.GetRawTransactionModel;

/**
 *
 * @author ssd
 */
public class TransferContractToMultisigPanelView extends javax.swing.JPanel {
    private String multisigAddress;
    private long vout;
    /**
     * Creates new form TransferContractToMultisigPanelView
     */
    public TransferContractToMultisigPanelView(String multisigAddress, String contractTransactionId) {
        initComponents();
        this.multisigAddress = multisigAddress;
        contractTransactionIdTextField.setText(contractTransactionId);
        voutTextField.setVisible(false);
        transactionIdOfTransferredContractTextField.setVisible(false);
        multisigAddressTextField.setText(multisigAddress);
        
        // fix this by getting txid from Register Contract tab
        GetRawTransactionModel getRawTransactionModel = RegistryServiceControl.getRawTransaction(contractTransactionIdTextField.getText());
        if(getRawTransactionModel.getError() == null){
            voutTextField.setVisible(true);
            voutTextField.setText(String.valueOf(getRawTransactionModel.getResult().getVout().get(0).getN()));
            vout = getRawTransactionModel.getResult().getVout().get(0).getN();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transferContractToMultisigAddressLable = new javax.swing.JLabel();
        contractTransactionIdLabel = new javax.swing.JLabel();
        contractTransactionIdTextField = new java.awt.TextField();
        transferContractToMultisigButton = new javax.swing.JButton();
        voutLabel = new javax.swing.JLabel();
        voutTextField = new java.awt.TextField();
        multisigAddressLabel = new javax.swing.JLabel();
        multisigAddressTextField = new java.awt.TextField();
        transactionIdOfTransferredContractLabel = new javax.swing.JLabel();
        transactionIdOfTransferredContractTextField = new java.awt.TextField();

        transferContractToMultisigAddressLable.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        transferContractToMultisigAddressLable.setText("Transfer Contract to Multisig Address");

        contractTransactionIdLabel.setText("Contract Transaction ID:");

        transferContractToMultisigButton.setText("Transfer");
        transferContractToMultisigButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferContractToMultisigButtonActionPerformed(evt);
            }
        });

        voutLabel.setText("Vout:");

        voutTextField.setEditable(false);

        multisigAddressLabel.setText("Multisig Address:");

        multisigAddressTextField.setEditable(false);

        transactionIdOfTransferredContractLabel.setText("Transaction ID of Transferred Contract:");

        transactionIdOfTransferredContractTextField.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(transferContractToMultisigAddressLable)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(contractTransactionIdLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(contractTransactionIdTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(transferContractToMultisigButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(voutLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(voutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(multisigAddressLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(multisigAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(transactionIdOfTransferredContractLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transactionIdOfTransferredContractTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transferContractToMultisigAddressLable)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contractTransactionIdLabel)
                    .addComponent(contractTransactionIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(voutLabel)
                    .addComponent(voutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(multisigAddressLabel)
                    .addComponent(multisigAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(transferContractToMultisigButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(transactionIdOfTransferredContractLabel)
                    .addComponent(transactionIdOfTransferredContractTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void transferContractToMultisigButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferContractToMultisigButtonActionPerformed
        String rawTxHex = RegistryServiceControl.createRawTransaction(contractTransactionIdTextField.getText(), vout, multisigAddress);
        String txIdOfTransferContractToMultisig = RegistryServiceControl.decodeRawTransaction(rawTxHex);
        String signedTx = RegistryServiceControl.signRawTransactionWithWallet(rawTxHex, "ord");
        String txIdOfTransferredContract = RegistryServiceControl.sendRawTransaction(signedTx, "ord");
        transactionIdOfTransferredContractTextField.setText(txIdOfTransferredContract);
    }//GEN-LAST:event_transferContractToMultisigButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contractTransactionIdLabel;
    private java.awt.TextField contractTransactionIdTextField;
    private javax.swing.JLabel multisigAddressLabel;
    private java.awt.TextField multisigAddressTextField;
    private javax.swing.JLabel transactionIdOfTransferredContractLabel;
    private java.awt.TextField transactionIdOfTransferredContractTextField;
    private javax.swing.JLabel transferContractToMultisigAddressLable;
    private javax.swing.JButton transferContractToMultisigButton;
    private javax.swing.JLabel voutLabel;
    private java.awt.TextField voutTextField;
    // End of variables declaration//GEN-END:variables
}
