/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package solution.view;

/**
 *
 * @author ssd
 */
public class VerifyTransactionsPanel extends javax.swing.JPanel {

    /**
     * Creates new form VerifyTransactions
     */
    public VerifyTransactionsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        verifyPaymentTransactionLabel = new javax.swing.JLabel();
        paymentTransactionIdLabel = new javax.swing.JLabel();
        paymentTransactionIdTextField = new java.awt.TextField();
        verifyPaymentButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        verifyPaymentTransactionLabel.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        verifyPaymentTransactionLabel.setText("Verify Payment Transaction");

        paymentTransactionIdLabel.setText("Payment Transaction ID:");

        verifyPaymentButton.setText("Verify");
        verifyPaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyPaymentButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(verifyPaymentTransactionLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(paymentTransactionIdLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paymentTransactionIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(verifyPaymentButton)
                    .addComponent(jLabel1))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(verifyPaymentTransactionLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paymentTransactionIdLabel)
                    .addComponent(paymentTransactionIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(verifyPaymentButton)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(164, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void verifyPaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyPaymentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verifyPaymentButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel paymentTransactionIdLabel;
    private java.awt.TextField paymentTransactionIdTextField;
    private javax.swing.JButton verifyPaymentButton;
    private javax.swing.JLabel verifyPaymentTransactionLabel;
    // End of variables declaration//GEN-END:variables
}
