/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package solution.view;

import solution.control.RegistryServiceControl;
import solution.model.GetBlockModel;
import solution.model.GetRawTransactionModel;
import solution.service.StringsService;

/**
 *
 * @author ssd
 */
public class VerifyContractSignaturesPanel extends javax.swing.JPanel {

    /**
     * Creates new form VerifyContractSignaturesPanel
     */
    public VerifyContractSignaturesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        verifyContractSignaturesLabel = new javax.swing.JLabel();
        signaturesConfirmationMessageLabel = new javax.swing.JLabel();
        confirmationsLabel = new javax.swing.JLabel();
        confirmationsTextField = new java.awt.TextField();
        confirmationBlockNumberLabel = new javax.swing.JLabel();
        confirmationBlockNumberTextField = new java.awt.TextField();
        recipientAddressLabel = new javax.swing.JLabel();
        blockHashLabel = new javax.swing.JLabel();
        recipientAddressTextField = new java.awt.TextField();
        blockHashTextField = new java.awt.TextField();
        amountSentLabel = new javax.swing.JLabel();
        paymentConfirmationMessageTextField = new java.awt.TextField();
        amountSentTextField = new java.awt.TextField();
        txIdOfSignedContractSentToRegistryAddressLabel = new javax.swing.JLabel();
        timeStampLabel = new javax.swing.JLabel();
        txIdOfSignedContractSentToRegistryAddressTextField = new java.awt.TextField();
        timeStampTextField = new java.awt.TextField();
        verifyPaymentButton = new javax.swing.JButton();
        buyerWalletPublicKeyLabel = new javax.swing.JLabel();
        ownerWalletPublicKeyLabel = new javax.swing.JLabel();
        ownerBuyerSignatureHexLabel = new javax.swing.JLabel();
        ownerBuyerSignatureHexTextField = new java.awt.TextField();
        buyerWalletPublicKeyTextField = new java.awt.TextField();
        onwerWalletPublicKeyTextField = new java.awt.TextField();

        verifyContractSignaturesLabel.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        verifyContractSignaturesLabel.setText("Verify Contract Signatures");

        signaturesConfirmationMessageLabel.setText("Signatures Confirmation Message:");

        confirmationsLabel.setText("Confirmations:");

        confirmationsTextField.setBackground(new java.awt.Color(242, 242, 242));
        confirmationsTextField.setEditable(false);

        confirmationBlockNumberLabel.setText("Confirmation Block Number:");

        confirmationBlockNumberTextField.setBackground(new java.awt.Color(242, 242, 242));
        confirmationBlockNumberTextField.setEditable(false);

        recipientAddressLabel.setText("Recipient Address:");

        blockHashLabel.setText("Block Hash:");

        recipientAddressTextField.setBackground(new java.awt.Color(242, 242, 242));

        blockHashTextField.setBackground(new java.awt.Color(242, 242, 242));
        blockHashTextField.setEditable(false);

        amountSentLabel.setText("Amount Sent:");

        paymentConfirmationMessageTextField.setBackground(new java.awt.Color(242, 242, 242));
        paymentConfirmationMessageTextField.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N

        amountSentTextField.setBackground(new java.awt.Color(242, 242, 242));

        txIdOfSignedContractSentToRegistryAddressLabel.setText("Transaction ID of Signed Contract Sent to Registry Office Address:");

        timeStampLabel.setText("Timestamp:");

        timeStampTextField.setBackground(new java.awt.Color(242, 242, 242));
        timeStampTextField.setEditable(false);

        verifyPaymentButton.setText("Verify");
        verifyPaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyPaymentButtonActionPerformed(evt);
            }
        });

        buyerWalletPublicKeyLabel.setText("Buyer Wallet Public Key:");

        ownerWalletPublicKeyLabel.setText("Owner Wallet Public Key:");

        ownerBuyerSignatureHexLabel.setText("Owner and Buyer Signature Hex:");

        ownerBuyerSignatureHexTextField.setBackground(new java.awt.Color(242, 242, 242));
        ownerBuyerSignatureHexTextField.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ownerBuyerSignatureHexLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ownerBuyerSignatureHexTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(verifyContractSignaturesLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txIdOfSignedContractSentToRegistryAddressLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txIdOfSignedContractSentToRegistryAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(timeStampLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(timeStampTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(verifyPaymentButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(signaturesConfirmationMessageLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paymentConfirmationMessageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(confirmationsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(confirmationsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(confirmationBlockNumberLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(confirmationBlockNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(blockHashLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(blockHashTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(recipientAddressLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(recipientAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(amountSentLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(amountSentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buyerWalletPublicKeyLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buyerWalletPublicKeyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ownerWalletPublicKeyLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(onwerWalletPublicKeyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(verifyContractSignaturesLabel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txIdOfSignedContractSentToRegistryAddressLabel)
                            .addComponent(txIdOfSignedContractSentToRegistryAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buyerWalletPublicKeyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buyerWalletPublicKeyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(ownerWalletPublicKeyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(onwerWalletPublicKeyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(verifyPaymentButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signaturesConfirmationMessageLabel)
                    .addComponent(paymentConfirmationMessageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmationsLabel)
                    .addComponent(confirmationsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmationBlockNumberLabel)
                    .addComponent(confirmationBlockNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(blockHashLabel)
                    .addComponent(blockHashTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timeStampTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeStampLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recipientAddressLabel)
                    .addComponent(recipientAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(amountSentLabel)
                    .addComponent(amountSentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ownerBuyerSignatureHexLabel)
                    .addComponent(ownerBuyerSignatureHexTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void verifyPaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyPaymentButtonActionPerformed

        String paymentTransactionId = txIdOfSignedContractSentToRegistryAddressTextField.getText();
        String buyerWalletPublicKey = buyerWalletPublicKeyTextField.getText();
        String ownerWalletPublicKey = onwerWalletPublicKeyTextField.getText();
                
        GetBlockModel getBlockModel = RegistryServiceControl.searchTransactionInBlocks(paymentTransactionId);
        if (getBlockModel != null){
            GetRawTransactionModel getRawTransactionModel = RegistryServiceControl.getRawTransaction(paymentTransactionId);
            String ownerBuyerSignatureHex = getRawTransactionModel.getResult().getHex();
            ownerBuyerSignatureHexTextField.setText(ownerBuyerSignatureHex);
            
            if (ownerBuyerSignatureHex.contains(ownerWalletPublicKey) && ownerBuyerSignatureHex.contains(buyerWalletPublicKey)){
            
                confirmationsTextField.setText(Long.toString(getBlockModel.getConfirmations()));
                confirmationBlockNumberTextField.setText(Long.toString(getBlockModel.getHeight()));
                blockHashTextField.setText(getBlockModel.getHash());
                String time = RegistryServiceControl.convertUnixEpochToUtcTime(getBlockModel.getTime());
                timeStampTextField.setText(time);
    
                String recipientAddress = getRawTransactionModel.getResult().getVout().get(0).getScriptPubKey().getAddress();
                recipientAddressTextField.setText(recipientAddress);
                String amountSent = Double.toString(getRawTransactionModel.getResult().getVout().get(0).getValue());
                amountSentTextField.setText(amountSent);

                paymentConfirmationMessageTextField.setText(StringsService.payment_has_been_confirmed_on_the_blockchain);

            }else{
                paymentConfirmationMessageTextField.setText(StringsService.payment_has_not_been_confirmed_on_the_blockchain);
            }
        }else{
            paymentConfirmationMessageTextField.setText(StringsService.payment_has_not_been_confirmed_on_the_blockchain);
        }
    }//GEN-LAST:event_verifyPaymentButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountSentLabel;
    private java.awt.TextField amountSentTextField;
    private javax.swing.JLabel blockHashLabel;
    private java.awt.TextField blockHashTextField;
    private javax.swing.JLabel buyerWalletPublicKeyLabel;
    private java.awt.TextField buyerWalletPublicKeyTextField;
    private javax.swing.JLabel confirmationBlockNumberLabel;
    private java.awt.TextField confirmationBlockNumberTextField;
    private javax.swing.JLabel confirmationsLabel;
    private java.awt.TextField confirmationsTextField;
    private java.awt.TextField onwerWalletPublicKeyTextField;
    private javax.swing.JLabel ownerBuyerSignatureHexLabel;
    private java.awt.TextField ownerBuyerSignatureHexTextField;
    private javax.swing.JLabel ownerWalletPublicKeyLabel;
    private java.awt.TextField paymentConfirmationMessageTextField;
    private javax.swing.JLabel recipientAddressLabel;
    private java.awt.TextField recipientAddressTextField;
    private javax.swing.JLabel signaturesConfirmationMessageLabel;
    private javax.swing.JLabel timeStampLabel;
    private java.awt.TextField timeStampTextField;
    private javax.swing.JLabel txIdOfSignedContractSentToRegistryAddressLabel;
    private java.awt.TextField txIdOfSignedContractSentToRegistryAddressTextField;
    private javax.swing.JLabel verifyContractSignaturesLabel;
    private javax.swing.JButton verifyPaymentButton;
    // End of variables declaration//GEN-END:variables
}
